name: Send MQTT Message

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      mqtt_topic:
        description: 'MQTT Topic'
        type: string
        required: true
        default: 'test/topic'
      mqtt_message:
        description: 'MQTT Message'
        type: string
        required: true
        default: 'Hello from GitHub Actions!'

jobs:
  publish-mqtt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Mosquitto Clients
        run: sudo apt-get update && sudo apt-get install -y mosquitto-clients

      - name: Publish MQTT Message
        run: |
          mosquitto_pub -h "${{ secrets.MQTT_HOST }}" \
           -p "${{ secrets.MQTT_PORT }}" \
           -u "${{ secrets.MQTT_USERNAME }}" \
           -P "${{ secrets.MQTT_PASSWORD }}" \
           -t "${{ inputs.mqtt_topic}}" \
           -m "${{ inputs.mqtt_message}}"
