name: Send MQTT Message

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  publish-mqtt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Mosquitto Clients
        run: sudo apt-get update && sudo apt-get install -y mosquitto-clients

      - name: Publish MQTT Message
        env:
          MQTT_HOST: ${{ secrets.MQTT_HOST }}
          MQTT_PORT: ${{ secrets.MQTT_PORT }}
          MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
        run: |
          mosquitto_pub -h "$MQTT_HOST" -p "$MQTT_PORT" -u "$MQTT_USERNAME" -P "$MQTT_PASSWORD" -t "test/topic" -m "Hello from GitHub Actions!"
