name: Triggered by Home Assistant

on:
  repository_dispatch:
    types:
      - homeassistant_event

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print message
        run: echo "Workflow triggered by Home Assistant!"
